### ISSUE TITLE
Precedes eat first column

### ISSUE THREAD

**Issue by beefeater7** [fent/vim-relative-indent#1]
As the screenshot demonstrates, my list behavior deviates a bit from the one in the GIF. Is there a user side fix I should know about?
![Ruby def getting hidden](https://user-images.githubusercontent.com/10468970/75722707-046bfa80-5cdb-11ea-9562-252d02b52b8c.png)

**Comment by fent** [comment]
I was able to reproduce this by opening two panes of the same file, then unsetting `list` with `:set nolist`. then after switching to the other pane, it miscalculated the amount of space on the left side like in your image

a temporary fix for this can be to run `:set list` or `:set nolist` again in your pane. I'll try to fix this in the next few days

**Comment by fent** [comment]
I just pushed a potential fix for this 😄 . please test it and let me know if things look good.

**Comment by beefeater7** [comment]
I gave it a shot, but it's still broken unfortunately.

I tried the stopgap solution also with :set no/list, but it doesn't help. Using one pane or two doesn't make a difference. 
![precedes-still](https://user-images.githubusercontent.com/10468970/77073324-62912100-69ef-11ea-875d-347ace0eec5b.png)

I hope you persist with this, the plugin is a great concept. If I had clearer instructions for the airline that would work too for me.

**Comment by fent** [comment]
I've been able to reproduce again :/. how are you calling the plugin, with the autocmd like in the readme?

my airline setup looks like this
```vim
let g:lightline = {
  \ 'colorscheme': 'wombat',
  \ 'active': {
  \   'left': [
  \     ['relative_indent', 'mode', 'paste'],
  \     ['readonly', 'filename', 'modified']
  \   ],
  \   'right': [['lineinfo'], ['percent'], ['fileformat', 'filetype']],
  \ },
  \ 'component': {
  \   'lineinfo': '%3l:%02v/%.4L'
  \ },
  \ 'component_function': {
  \   'relative_indent': 'LightlineRelativeIndent',
  \   'fileformat': 'LightlineFileformat',
  \   'filetype': 'LightlineFiletype'
  \ },
  \ }
function! LightlineRelativeIndent()
  return repeat('<', get(w:, 'relative_indent_level', 0))
endfunction

```

**Comment by fent** [comment]
do you have your vim config files uploaded anywhere? would be worth knowing if some rogue option can affect this plugin. I just found out that `sidescrolloff` can affect it (but that option isn't causing this issue)

**Comment by beefeater7** [comment]
My configs were a bit messy, so I tried to reduce them for your convenience.
```
#sysinit.vim
lan en
set conceallevel=2
set mouse=a
set number
set relativenumber
set shiftwidth=3
set tabstop=3

if has('persistent_undo')
    let target_path = expand('~/.config/vim-persisted-undo/')
    if !isdirectory(target_path)
        call system('mkdir -p ' . target_path)
    endif
    let &undodir = target_path
    set undofile
endif

" Undo - Redo
"    u - U
nnoremap U 
" Undo by Write
nnoremap <M-u> :ear 1f<CR>
nnoremap <M-U> :lat 1f<CR>
```
``` 
#init.vim
call plug#begin(stdpath('data') . '/plugged')
	Plug 'fent/vim-relative-indent' " precede bug: reported
call plug#end()

set nowrap
augroup relative_indent
  autocmd!
  " Apply to all filetypes except markdown and quickfix
  autocmd FileType * :RelativeIndentEnable
  autocmd FileType markdown :setlocal wrap
augroup END
set listchars+=precedes:<
set list
```
Hope it helps... The first two levels of indentation tend to look fine, for what it's worth.

[My testing ground.](https://github.com/fent/vim-relative-indent/files/4402808/lipsum.txt)

**Comment by fent** [comment]
hi, it's been a long time, but i just pushed a potential fix. would be great if you could test on your setup to confirm it working

**Comment by fent** [comment]
will assume fixed. feel free to re-open if not

**Comment by beefeater7** [comment]
Hello, sorry I didn't see this until recently. I wiped Windows and started fresh with a Linux distro, so I don't know if my setup can provide relevant data on the fix.

**Comment by fent** [comment]
well if you feel like installing it again and trying it out, feel free
